language: java
jdk:
    - oraclejdk8
sudo: required
services:
  - docker
script:
    - mvn dockerfile:build
after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_USERNAME/bci-ai-runner